### ISSUE TITLE
feature: support save to the current project directory 

### ISSUE THREAD

**Issue by wenzewoo** [wenzewoo/jetbrains-code-remark#12]
- ~/.code-remark/{projectName}
- {projectPath}/.code-remark

**Comment by guobin211** [comment]
support save to some file

- {projectPath}/.vscode/code-remark.xml
- {projectPath}/.idea/code-remark.xml

**Comment by wenzewoo** [comment]
https://github.com/wenzewoo/jetbrains-code-remark/releases/tag/1.4.0
