### ISSUE TITLE
feature: use git sync bookmark

### ISSUE THREAD

**Issue by guobin211** [wenzewoo/jetbrains-code-remark#14]
add bookmark file to project
1.  {project}/.vscode/book-mark.json
2. {project}/.idea/book-mark.json

**Comment by fufenghua** [comment]
+1
现在是放到user/.code-remark下的，并不跟项目走，想纳入到git控制中

**Comment by wenzewoo** [comment]
https://github.com/wenzewoo/jetbrains-code-remark/releases/tag/1.4.0
https://plugins.jetbrains.com/plugin/17805-code-remark - 审核中
