### ISSUE TITLE
Keyboard Shortcut conflict

### ISSUE THREAD

**Issue by Matthiasvanderhallen** [wenzewoo/jetbrains-code-remark#3]
Please consider using a different default keyboard shortcut: currently it registers shift+r, which conflicts with, well, a capital R...
We can change it, but after update it resets itself.

**Comment by wenzewoo** [comment]
Remove add/navigation default shortcuts
https://github.com/wenzewoo/jetbrains-code-remark/commit/39f815c5d0d08f615bf8ab81c9b2e7c3a9f7ddd0
