### ISSUE TITLE
IDEA报错提示 error

### ISSUE THREAD

**Issue by 786659214** [wenzewoo/jetbrains-code-remark#6]
![Uploading 953ed8d397b8f640dc474152464a820.png…]()

**Comment by 786659214** [comment]
![953ed8d397b8f640dc474152464a820](https://user-images.githubusercontent.com/49685173/145542966-dbfec3b0-904c-4d88-aae5-b28239aee9e9.png)

**Comment by wenzewoo** [comment]
https://github.com/wenzewoo/jetbrains-code-remark/commit/fd7e19787deaaf14c3320b4310807b8ccf11ba9a
