### ISSUE TITLE
IDEA2021.3.1版本已经移除了Favorites

### ISSUE THREAD

**Issue by ZJesse** [wenzewoo/jetbrains-code-remark#7]
IDEA2021.3.1版本Favorites和Remarks合并只保留了Remarks，View -> Tool Windows -> Favorites视图也就没有了，就看不了项目里所有的备注信息了

**Comment by wenzewoo** [comment]
考虑将Remarks移出Favorites视图。

**Comment by xiaopenghust** [comment]
预计啥时候能更新呢?非常期待

**Comment by cnyondy** [comment]
修复在bookmark视图中的备注信息显示，IDE版本要求在2022.2以上
https://github.com/cnyondy/jetbrains-code-remark/releases/tag/1.3.6.3-SNAPSHOT
